[package]
name = "drv-sprot-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-idol-err = {path = "../../lib/derive-idol-err" }
userlib = {path = "../../sys/userlib"}
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.6.1"
ringbuf = {path = "../../lib/ringbuf"}
crc = "3.0.0"
memoffset = {version = "0.6.5", default-features = false}
if_chain = "1"

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}
